### ISSUE TITLE
How to not encode Unicode characters?

### ISSUE THREAD

**Issue by ooker777** [jeff-hykin/deno_bundle#1]
I prefer to have the Unicode characters in my script not being encoded. I don't see the [`charset`](https://esbuild.github.io/api/#charset "esbuild - API") option is built. Would you consider this a good feature?

**Comment by jeff-hykin** [comment]
Sure, when I get a chance I'll try to add this to the CLI options!

**Comment by jeff-hykin** [comment]
Turns out it was supported just undocumented (`deno_bundle --charset="utf8" ./example.js`)

**Comment by jeff-hykin** [comment]
Okay I pushed an update, adding it as an option and setting utf8 as the default since that was the `deno bundle` behavior
