### ISSUE TITLE
Does it support React?

### ISSUE THREAD

**Issue by tylerlong** [jeff-hykin/deno_bundle#2]
https://github.com/tylerlong/deno-react-demo/blob/main/src/index.tsx

As I tested, it doesn't support React.

After bundling and I tried to run it in browser, there is an error: index.js:5685 Uncaught ReferenceError: h is not defined

esbuild works: https://github.com/tylerlong/deno-react-demo/blob/main/bundle.ts

**Comment by jeff-hykin** [comment]
Answe: not really

> Uncaught ReferenceError: h is not defined

Yep, the original `deno bundle` was not designed for web bundling. Its only for CLI bundling.

However, I do think it supports JSX. That said, the files that use JSX need a header I believe:

```
/** @jsx yourFunctionNameHere */
/// <reference no-default-lib="true"/>
/// <reference lib="dom" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />
```

So I think you would need to import react `createElement`. Then replace yourFunctionNameHere with `createElement`

**Comment by tylerlong** [comment]
Thanks. I think most people need a bundler for web bundling. 
Server side bundling doesn't make much sense, at least it's not mandatory. You can run a un-bundled server-side app. Bundling a server-app may provide some benefits, but most people may not bother doing it.

Without above said, it's not the fault of this library/tool since it is designed to support server-side bundling only.

Feel free to close the ticket.

**Comment by jeff-hykin** [comment]
Yup, thats actually exactly why the Deno team removed it as a built-in tool

> the deno bundle command had a huge mismatch in what users expected (a general purpose bundler with a bunch of setting knobs) with what it really was (a dedicated tool to create a single file out of a Deno specific project). It was conceived in the early days of Deno, when Node.js compatibility was very nascent. Additionally the underlying implementation (swc_bundler) hasn't been improving a lot. We decided it's best to deprecate and remove it for Deno 2.

https://github.com/denoland/deno/issues/11073#issuecomment-2331253599

This tool was made to preserve the Deno 1.x bundler experience

**Comment by jeff-hykin** [comment]
> Server side bundling doesn't make much sense

Its got a few more uses that you might expect. 

1. I use it all the time as a CLI tool, not a build tool. Ex: porting a library to deno, or making a library work in the broswer, or making a cross-platform offline script.
2. In truth, the bundler is not really "server side". It bundles any pure JavaScript code (e.g. the ECMA script code with full esm imports, no CSS, wasm, JSX, etc). So if you're a purist like me, it actually does work for simple web bundling, client or server.
